### ISSUE TITLE
请问流媒体服务器是部署在CentOS上还是和后端SpringBoot一样部署在WindowsPC上呢

### ISSUE THREAD

**Issue by QuantumCat8823** [xiwang-online/People-Detection-System#4]

**Comment by xiwang-online** [comment]
我都是通过docker来部署的，不管是在CentOS、Ubuntu，还是WindowsPC还是都可以，流媒体服务器用的是这个项目：https://github.com/alfg/docker-nginx-rtmp

**Comment by QuantumCat8823** [comment]
好的，谢谢大佬！我部署在CentOS上了。不过Python上有出了问题，捣鼓了一下午了，就是我将四个摄像头的IP都设置为大佬您的那个test.mp4想测试一下Python端的时候，一直报错ValueError
![1](https://github.com/xiwang-online/People-Detection-System/assets/136867062/4e67d27e-18c1-49ca-a100-b4edeb12c6af)ValueError: operands could not be broadcast together with shapes (24,512) (25,1)
![2](https://github.com/xiwang-online/People-Detection-System/assets/136867062/80fc4130-7d00-4f37-a2d0-c9e1d2f92da4)

**Comment by QuantumCat8823** [comment]
> 我都是通过docker来部署的，不管是在CentOS、Ubuntu，还是WindowsPC都可以，流媒体服务器用的是这个项目：https://github.com/alfg/docker-nginx-rtmp

大佬见上

**Comment by QuantumCat8823** [comment]
已经解决

**Comment by LFG12** [comment]
请问如何解决的呀大佬，我也想先使用本地视频测试一下
